---
title: "a2_janderson+wlien"
format: pdf
editor: visual
---

```{r}
#| echo: false
```

# SETUP

## LOAD PACKAGES

```{r}
#install.packages("dataRetrieval")
library(dataRetrieval)
library(tidyverse)
```

## LOAD DATA (RETIRED)

```{r}
siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010"  # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"

temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate)

write_csv(temp_data, "data.csv")
```

## READ DATA

```{r}
data <- read_csv("data.csv")
```

```{r}
# rename columns for clarity
colnames(data) <- c("agency_cd", "site_no", "Date", "temp_C")
# extract some date info for use later
data$month = month(temp_data$Date, label=TRUE)
data$year = year(temp_data$Date)

# check by plotting
ggplot(data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_minimal()
```

# Summary Statistic

## mean, max, min temperature for each site

```{r}
stream_sum <- data |> 
  select("site_no","temp_C") |>
  group_by(site_no) |>
  summarise(mean_temp=mean(temp_C), sd_temp=sd(temp_C), min_temp=min(temp_C), max_temp=max(temp_C))

stream_sum
```


# WL Branch
## August data
```{r}
# filter for July temperatures
aug_data <- subset(data, month == "八月")
# fit a GLM model to see if there is a trend in July temperatures over time, separated by sit
aug_model <- glm(temp_C ~ year*site_no, data = aug_data)
summary(aug_model)
```

# JA Branch

## march data

```{r}
library(tidyverse) 
# filter for march temperatures
march_data <- subset(data, month == "Mar")
# fit a GLM model to see if there is a trend in March temperatures over time, separated by site
march_model <- glm(temp_C ~ year*site_no, data = march_data)
summary(march_model)
```
